const characters = [
  {char: '1', type: 0},
  {char: '2', type: 0},
  {char: '3', type: 0},
  {char: '4', type: 0},
  {char: '5', type: 0},
  {char: '6', type: 0},
  {char: '7', type: 0},
  {char: '8', type: 0},
  {char: '9', type: 0},
  {char: '0', type: 0},
  {char: 'q', type: 0},
  {char: 'w', type: 0},
  {char: 'e', type: 0},
  {char: 'r', type: 0},
  {char: 't', type: 0},
  {char: 'y', type: 0},
  {char: 'u', type: 0},
  {char: 'i', type: 0},
  {char: 'o', type: 0},
  {char: 'p', type: 0},
  {char: 'a', type: 0},
  {char: 's', type: 0},
  {char: 'd', type: 0},
  {char: 'f', type: 0},
  {char: 'g', type: 0},
  {char: 'h', type: 0},
  {char: 'j', type: 0},
  {char: 'k', type: 0},
  {char: 'l', type: 0},
  {char: '😀', type: 1},
  {char: 'z', type: 0},
  {char: 'x', type: 0},
  {char: 'c', type: 0},
  {char: 'v', type: 0},
  {char: 'b', type: 0},
  {char: 'n', type: 0},
  {char: 'm', type: 0},
  {char: '?', type: 0},
  {char: '!', type: 0},
  {char: '.', type: 0},
  {char:  ' ', type: 0},
]

const emojis = [
  { char: '😀', type: 0 },
  { char: '😉', type: 0 },
  { char: '🙄', type: 0 },
  { char: '😊', type: 0 },
  { char: '😋', type: 0 },
  { char: '😎', type: 0 },
  { char: '🤩', type: 0 },
  { char: '🤔', type: 0 },
  { char: '🤗', type: 0 },
  { char: '🤨', type: 0 },
  { char: '😍', type: 0 },
  { char: '😘', type: 0 },
  { char: '😯', type: 0 },
  { char: '😴', type: 0 },
  { char: '😜', type: 0 },
  { char: '🤤', type: 0 },
  { char: '😒', type: 0 },
  { char: '😖', type: 0 },
  { char: '🤯', type: 0 },
  { char: '😬', type: 0 },
  { char: '😱', type: 0 },
  { char: '😳', type: 0 },
  { char: '🤪', type: 0 },
  { char: '😡', type: 0 },
  { char: '😇', type: 0 },
  { char: '👍', type: 0 },
  { char: '👎', type: 0 },
  { char: '👌', type: 0 },
  { char: '🤞', type: 0 },
  { char: 'A', type: 1 },
  { char: '👋', type: 0 },
  { char: '💪', type: 0 },
  { char: '🐼', type: 0 },
  { char: '🐷', type: 0 },
  { char: '🐽', type: 0 },
  { char: '🌻', type: 0 },
  { char: '❤️', type: 0 },
  { char: '🙊', type: 0 },
  { char: '🙉', type: 0 },
  { char: '🙈', type: 0 },
  { char: ' ', type: 0 },
]
export default [characters, emojis]